### PR TITLE
Update README.md with more detailed introduction summery

### PR DESCRIPTION
**Pull request by Hedda**
@MattWestb  Update README.md with a more detailed introduction summary (and also got Grammarly installed for better spelling and grammar, but did not have time to spellcheck everything at this time).

### CODE REVIEW

**Comment by Hedda** [comment]
@MattWestb Bump ;)

**Comment by Hedda** [comment]
@MattWestb Closed without comment on the reason for closing?

**Comment by MattWestb** [comment]
To much changes is made to the master that is being lost if marger it.

**Comment by Hedda** [comment]
But since no comment, you do not want a rebased version or a new PR?

**Comment by MattWestb** [comment]
This git is more or less one reference scratchpad for my work to sharing the knowledge to other users that finding it interesting and can using the information / experience for their projects.
I dont intend doing it as one reference wikipedia with global coverage only as sharing experience that i have made.

If you like doing one global covered wikipedia feel free making one.

**Pull request closed without merging**
